spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: validate
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/db
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: socket